[package]
name = "cost"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
schema = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
